### PR TITLE
Move APR to consume RabbitMQ events instead of Kafka

### PR DESCRIPTION
**Pull request by ashkan18**
# Problem
We've decided to move from Kafka to RabbitMQ as our event stream. 

# Changes
This PR
- stops listening on Kafka, removes all dependencies.
- adds `amqp` dependency and needed configs
- Adds a GenServer based service for listening on RabbitMQ topics and a `BroadcastService` which is responsible for broadcasting events to websockets.

# Migration
Remove Kafka related env variables and add
```
RABBITMQ_HOST=
RABBITMQ_PORT=
RABBITMQ_USER=
RABBITMQ_PASSWORD=
```
# Follow up
Add `purchases` and `auctions` topics.

### CODE REVIEW

**Comment by acjay** [comment]
I read "Problem" and was like, "oh crap, what happened?", LOL.

**Comment by ashkan18** [comment]
haha @acjay ran out of titles 👍 This is also APR which is just the UI app not the slack bot.

**Comment by orta** [comment]
nice one, this looks good and simple 👍

**Comment by orta** [comment]
bye user stream. I can imagine that one can get pretty messy.

**Pull request merged**
