### PR TITLE
deploy from CI build

### PR DESCRIPTION
**Pull request by izakp**
Gets the latest build from CI and deploys it in a Capistrano-like fashion.  No more git checkouts or compiling as part of the build process.

### CODE REVIEW

**Comment by joeyAghion** [comment]
👀 

```
** (Mix.Config.LoadError) could not load config config/.exs
    ** (Code.LoadError) could not load /home/ubuntu/APR/config/.exs
    (elixir) lib/code.ex:662: Code.find_file/2
    (elixir) lib/code.ex:295: Code.eval_file/2
```

**Comment by izakp** [comment]
@joeyAghion yea fixed - see my last commit about Circle not injecting environment vars into PR builds from forks

**Comment by izakp** [comment]
@joeyAghion that check is failing due to the `mix test` step but these are just cookbook changes - so ready to deploy this

**Comment by joeyAghion** [comment]
OK. @ashkan18 let me know if/how I can help with the build failures.

**Comment by ashkan18** [comment]
Sorry I haven't been helpful on APR side, I will take a look at this, `PageController` in APR pretty much doesn't do anything other than loading js files, not sure why test is broken but I'll take a look.

**Pull request merged**
